name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install black isort flake8
      - name: Check formatting with Black
        run: black --check .
      - name: Check import sorting with isort
        run: isort . --check-only
      - name: Lint with flake8
        run: flake8 wanderer/

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
      - name: Install tox
        run: pip install tox
      - name: Run pylint
        run: tox -e pylint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
      - name: Install tox
        run: pip install tox
      - name: Run tests
        run: tox -e py$(echo ${{ matrix.python-version }} | tr -d .)-django42
